### ISSUE TITLE
Support nested SVG elements.

### ISSUE THREAD

**Issue by mbostock** [mbostock/svjimmy#5]
We should only render the outermost SVG.

**Comment by seemantk** [comment]
These might well be edge cases, but there are legitimate reasons for nesting SVGs, where all the SVGs play a role (but the inner SVGs have the content):
- [Mimic relative positioning](https://sarasoueidan.com/blog/mimic-relative-positioning-in-svg/)
- [Zoom/Pan with viewbox and nested SVG](http://ribbon.humdrum.org)  (same example from the other ticket)
  - [A related bl.ock](https://bl.ocks.org/seemantk/5ec5698ac25c869b3e8c1261f6beaac4)

Not sure what heuristics could be used, though.

**Comment by mbostock** [comment]
Are you suggesting that there should be different behavior than rendering only the outermost SVG element, and if so, what behavior are you suggesting?

**Comment by seemantk** [comment]
In the use cases I've cited, the outermost svg determines the dimensions and coordinate system and the inner ones contain the visually interesting svg elements.

For example, on that Josquin page, you would only get a few blank png images with the current behavior..

**Comment by mbostock** [comment]
Rendering the outermost SVG element includes whatever content is in the contained SVG elements. There’s still the issue of dropping the external styles, but on the Josquin example, you get five images.

The “viewer”:
![untitled](https://cloud.githubusercontent.com/assets/230541/22750095/60e9e114-ede4-11e6-92f6-77df4392f91d.png)

The “navigator” (blank because it uses external styles):
![untitled-6](https://cloud.githubusercontent.com/assets/230541/22750128/7c16265a-ede4-11e6-8b8b-559553da52ce.png)

And three icons comprising the “legend”:
![untitled-8](https://cloud.githubusercontent.com/assets/230541/22750144/8caa75fc-ede4-11e6-8b9b-1c83fffd62ba.png)
![untitled-9](https://cloud.githubusercontent.com/assets/230541/22750145/8cbade2e-ede4-11e6-9c99-42897c95af68.png)
![untitled-10](https://cloud.githubusercontent.com/assets/230541/22750146/8cc531d0-ede4-11e6-83a8-1f26e0e21a4d.png)
